server:
  port: 8443
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3300/article?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    database: 2
    host: localhost
    port: 6666
    password: myRedis
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 9
        min-idle: 0
    timeout: 3000ms
  boot:
    admin:
      client:
        url: http://localhost:8123
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"



BaseHost: localhost:8443